### 1. Get all boxes
GET http://localhost:8080/api/boxes


### 2. Create a new box
POST http://localhost:8080/api/boxes
Content-Type: application/json

{
  "boxName": "Matcha Lover Box",
  "boxPrice": 299,
  "items": [
    {
      "itemName": "Matcha Cookie",
      "itemPrice": 60,
      "itemAmount": 5
    },
    {
      "itemName": "Matcha Mochi",
      "itemPrice": 75,
      "itemAmount": 3
    },
    {
      "itemName": "Matcha Roll Cake",
      "itemPrice": 90,
      "itemAmount": 4
    }
  ]
}


### 3. Get boxes by boxName
GET http://localhost:8080/api/boxes/boxname/Matcha Lover Box


### 4. Randomly select 2 items (no stock reduction)
GET http://localhost:8080/api/boxes/boxname/Matcha Lover Box/random?count=2


### 5. Purchase 1 box (1 item, reduce stock)
POST http://localhost:8080/api/boxes/purchase/Matcha Lover Box


### 6. Purchase 3 boxes
POST http://localhost:8080/api/boxes/purchase/Matcha Lover Box?quantity=3


### 7. Purchase multiple box themes
POST http://localhost:8080/api/boxes/purchase
Content-Type: application/json

[
  {
    "boxName": "Matcha Lover Box",
    "quantity": 2
  },
  {
    "boxName": "Choco Dream Box",
    "quantity": 1
  }
]
